### ISSUE TITLE
If too many colonists you cannot see the task time restriction menu area.

### ISSUE THREAD

**Issue by thakyZ** [fluffy-mods/WorkTab#113]
I have made too many androids and now the area of the work tab where you can restrict the time that tasks are done doesn't show up anymore. I have tested it with a new save and the area does show, so it's not a mod compatibility issue. I think maybe a scroll bar may be good to be able to view it. Anyways here is an image of the issue:
![image](https://user-images.githubusercontent.com/950594/56241739-7992fa80-604b-11e9-85b9-113a5513251a.png)

**Comment by FluffierThanThou** [comment]
I'm unable to replicate this, it works as expected on my machine, see the below screenshot. I suspect that whatever mod adds the 'colonists' bar on top of the window is moving all the other content down, and not caring about the available space. 

![image.png](https://zube.io/files/fluffy-mods/82078121ba68ac0986d89ba3889de172-image.png)
