### ISSUE TITLE
UI Scaling

### ISSUE THREAD

**Issue by dfisheritp** [fluffy-mods/WorkTab#121]
I need to invest in some glasses but the UI for the work tab seems to be hard coded and does not work when enlarging the scale. On an ultrawide 29' (~2.5k x ~1k pixels) screen it's very difficult to read.

I enlarged the UI scale to 1.25 and it's all sorts of wonky.

Looking for something about 10-15% larger so I can read the subcategories.

**Comment by ionstorm66** [comment]
Duplicate of #77
