### ISSUE TITLE
Default priority to 9

### ISSUE THREAD

**Issue by JaJe92** [fluffy-mods/WorkTab#122]
Hi Fluffy!

I want to suggest you implement a simple button on mod settings that allow us selecting the default number priority from 3 to any number. This way I no longer set default priority manually to all my pawns to 9 and then increase priority for each work type I need.

Thank you.

**Comment by FluffierThanThou** [comment]
thanks for the suggestion, I've jsut implemented it (which was a lot harder than it sounds!)

**Comment by frenchiveruti** [comment]
> thanks for the suggestion, I've jsut implemented it (which was a lot harder than it sounds!)

No fluffy, thank you bud, your mods are great and your work is great.
