### ISSUE TITLE
Work tab UI improvement idea to expand.

### ISSUE THREAD

**Issue by JaJe92** [fluffy-mods/WorkTab#124]
**Problem description**
Right now whenI want to give my pawn a specific work from sub-category I have to press 'expand all priorities' and struggling a bit to find exactly what I am looking for since the list shown is too long.

**Describe the solution**
A simple solution would be implementing a button or even better, pressing the task and expand only all priorities from that category for example like this:

<img src=https://i.imgur.com/rKWUdHf.png>

What do you think? This way would make things even simple to give specific task like giving my pawn the ability to butcher but not to cook rather than expanding all priorities and looking for buthering sub-category.

**Comment by FluffierThanThou** [comment]
You'll be happy to hear this feature is already in the mod: use `CTRL + Click` to expand any columns that have 'sub' jobs.
