### ISSUE TITLE
Tabbed Extended View

### ISSUE THREAD

**Issue by Electrocutor** [fluffy-mods/WorkTab#129]
**Feature Request**

**Problem Description**
When using the extended view of the work tab, the amount of horizontal span to cover all of the different actions is unruly; especially so when mods are also involved.

**Describe the Solution**
Ideally, I think it would be much more manageable if each basic group of actions got their own tab when switching to the extended view. This could also allow the priority number to be set next to the tab for the entire category (if the UI allows such a thing).

**Comment by FluffierThanThou** [comment]
You are aware that you can expand/collapse individual columns by `Ctrl+clicking` them?
